#!/usr/bin/env bash
# Configures a new Ubuntu machine to respect requirements

# Update Ubuntu repository
sudo apt-get update -y

# install Nginx
sudo apt-get install nginx -y

# Write the message to index file
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Start Nginx Server
sudo service nginx start
