#!/usr/bin/env bash
# Installs, configures, and starts the server

sudo apt-get -y update

sudo apt-get -y install nginx

sudo mkdir -p /etc/nginx/html

echo "Hello World" | sudo tee /etc/nginx/html/index.html

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx restart
