#!/usr/bin/env bash
# Installs, configures, and starts the server

sudo apt-get -y update

sudo apt-get -y install nginx

sudo mkdir -p /etc/nginx/html

echo "Hello World" | sudo tee /etc/nginx/html/index.html

printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" | sudo tee -a /etc/nginx/sites-available/default

echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/redirect

sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

sudo nginx -t
sudo service nginx restart
