#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Update packages
sudo apt-get update
sudo apt-get -y upgrade

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
printf %s "
  frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

  backend webservers
    balance roundrobin
    server 363691-web-01 100.24.236.248:80 check
    server 363691-web-02 100.26.151.181:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
