#!/usr/bin/env bash
# Displays Best School 10 times, but for the 9th iteration,
# displays Best School and then Hi on a new line.

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "$i Hi"
	else
		echo "$i Best School"
	fi
	((i++))
done
