#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on web-01

sudo apt update
sudo apt install ufw -y

sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

sudo ufw disable
sudo ufw enable

sudo ufw default deny incoming
sudo ufw default allow outgoing

sufo ufw allow 22/tcp
sufo ufw allow 443/tcp
sufo ufw allow 80/tcp
